### ISSUE TITLE
Compile on Arch Raspi

### ISSUE THREAD

**Issue by Klex167** [raspberrypi/quake3#5]
Hello, 

I try to compile quake3 on the Raspberry Pi with Arch Linux.
I used this tutorial: http://kittyhawkrpi.blogspot.de/2012/10/building-quake-3-on-arch-linux.html

But when I try to build, i get an error...

this is my console output:
Welcome to Arch Linux ARM

     Website: http://archlinuxarm.org
       Forum: http://archlinuxarm.org/forum
         IRC: #archlinux-arm on irc.Freenode.net

[alexander@tvpi ~]$ sudo pacman -Syu base-devel nano git

Wir gehen davon aus, dass der lokale Systemadministrator Ihnen die
Regeln erklärt hat.  Normalerweise läuft es auf drei Regeln hinaus:

    #1) Resprektieren Sie die Privatsphäre anderer.
    #2) Denken Sie nach bevor Sie tippen.
    #3) Mit großer Macht kommt große Verantwortung.

[sudo] password for alexander: 
:: Synchronisiere Paketdatenbanken...
 core ist aktuell
 extra ist aktuell
 community                               2,2 MiB   418K/s 00:05 [##################################] 100%
 alarm ist aktuell
 aur ist aktuell
:: Es sind 26 Mitglieder in der Gruppe base-devel:
:: Repositorium core
   1) autoconf  2) automake  3) binutils  4) bison  5) fakeroot  6) file  7) findutils  8) flex  9) gawk
   10) gcc  11) gettext  12) grep  13) groff  14) gzip  15) libtool  16) libutil-linux  17) m4  18) make
   19) pacman  20) patch  21) pkg-config  22) sed  23) sudo  24) texinfo  25) util-linux  26) which

Geben Sie eine Auswahl ein (Voreinstellung=alle): 
Warnung: autoconf-2.69-1 ist aktuell -- Reinstalliere
Warnung: automake-1.14.1-1 ist aktuell -- Reinstalliere
Warnung: binutils-2.24-1 ist aktuell -- Reinstalliere
Warnung: bison-3.0.2-1 ist aktuell -- Reinstalliere
Warnung: fakeroot-1.20-1 ist aktuell -- Reinstalliere
Warnung: file-5.18-1 ist aktuell -- Reinstalliere
Warnung: findutils-4.4.2-5 ist aktuell -- Reinstalliere
Warnung: flex-2.5.39-1 ist aktuell -- Reinstalliere
Warnung: gawk-4.1.0-2.1 ist aktuell -- Reinstalliere
Warnung: gcc-4.8.2-7 ist aktuell -- Reinstalliere
Warnung: gettext-0.18.3.2-1 ist aktuell -- Reinstalliere
Warnung: grep-2.18-1 ist aktuell -- Reinstalliere
Warnung: groff-1.22.2-6 ist aktuell -- Reinstalliere
Warnung: gzip-1.6-1 ist aktuell -- Reinstalliere
Warnung: libtool-2.4.2-12 ist aktuell -- Reinstalliere
Warnung: libutil-linux-2.24.1-6 ist aktuell -- Reinstalliere
Warnung: m4-1.4.17-1 ist aktuell -- Reinstalliere
Warnung: make-4.0-2 ist aktuell -- Reinstalliere
Warnung: pacman-4.1.2-5.1 ist aktuell -- Reinstalliere
Warnung: patch-2.7.1-2 ist aktuell -- Reinstalliere
Warnung: pkg-config-0.28-1 ist aktuell -- Reinstalliere
Warnung: sed-4.2.2-3 ist aktuell -- Reinstalliere
Warnung: sudo-1.8.10.p2-1 ist aktuell -- Reinstalliere
Warnung: texinfo-5.2-2 ist aktuell -- Reinstalliere
Warnung: util-linux-2.24.1-6 ist aktuell -- Reinstalliere
Warnung: which-2.20-6 ist aktuell -- Reinstalliere
Warnung: nano-2.2.6-2 ist aktuell -- Reinstalliere
Warnung: git-1.9.2-1 ist aktuell -- Reinstalliere
:: Starte komplette Systemaktualisierung...
Löse Abhängigkeiten auf...
Suche nach Zwischenkonflikten...

Pakete (28): autoconf-2.69-1  automake-1.14.1-1  binutils-2.24-1  bison-3.0.2-1  fakeroot-1.20-1
             file-5.18-1  findutils-4.4.2-5  flex-2.5.39-1  gawk-4.1.0-2.1  gcc-4.8.2-7
             gettext-0.18.3.2-1  git-1.9.2-1  grep-2.18-1  groff-1.22.2-6  gzip-1.6-1  libtool-2.4.2-12
             libutil-linux-2.24.1-6  m4-1.4.17-1  make-4.0-2  nano-2.2.6-2  pacman-4.1.2-5.1
             patch-2.7.1-2  pkg-config-0.28-1  sed-4.2.2-3  sudo-1.8.10.p2-1  texinfo-5.2-2
             util-linux-2.24.1-6  which-2.20-6

Gesamtgröße des Downloads:                 0,28 MiB
Gesamtgröße der zu installierenden Pakete: 160,56 MiB
Größendifferenz der Aktualisierung:        0,00 MiB

:: Installation fortsetzen?  [J/n] j
:: Empfange Pakete...
 nano-2.2.6-2-armv6h                   284,7 KiB   319K/s 00:01 [##################################] 100%
(28/28) Prüfe Schlüssel im Schlüsselring                        [##################################] 100%
(28/28) Überprüfe Paket-Integrität                              [##################################] 100%
(28/28) Lade Paket-Dateien                                      [##################################] 100%
(28/28) Prüfe auf Dateikonflikte                                [##################################] 100%
(28/28) Überprüfe verfügbaren Festplattenspeicher               [##################################] 100%
( 1/28) Installiere gawk                                        [##################################] 100%
( 2/28) Installiere m4                                          [##################################] 100%
( 3/28) Installiere autoconf                                    [##################################] 100%
( 4/28) Installiere automake                                    [##################################] 100%
( 5/28) Installiere binutils                                    [##################################] 100%
( 6/28) Installiere bison                                       [##################################] 100%
( 7/28) Installiere sed                                         [##################################] 100%
( 8/28) Installiere libutil-linux                               [##################################] 100%
( 9/28) Installiere util-linux                                  [##################################] 100%
(10/28) Installiere fakeroot                                    [##################################] 100%
(11/28) Installiere file                                        [##################################] 100%
(12/28) Installiere findutils                                   [##################################] 100%
(13/28) Installiere flex                                        [##################################] 100%
(14/28) Installiere gcc                                         [##################################] 100%
(15/28) Installiere gettext                                     [##################################] 100%
(16/28) Installiere grep                                        [##################################] 100%
(17/28) Installiere groff                                       [##################################] 100%
(18/28) Installiere gzip                                        [##################################] 100%
(19/28) Installiere libtool                                     [##################################] 100%
(20/28) Installiere make                                        [##################################] 100%
(21/28) Installiere pacman                                      [##################################] 100%
(22/28) Installiere patch                                       [##################################] 100%
(23/28) Installiere pkg-config                                  [##################################] 100%
(24/28) Installiere sudo                                        [##################################] 100%
(25/28) Installiere texinfo                                     [##################################] 100%
(26/28) Installiere which                                       [##################################] 100%
(27/28) Installiere nano                                        [##################################] 100%
(28/28) Installiere git                                         [##################################] 100%

[alexander@tvpi ~]$ git clone https://github.com/raspberrypi/quake3.git
Klone nach 'quake3'...
remote: Reusing existing pack: 789, done.
remote: Total 789 (delta 0), reused 0 (delta 0)
Empfange Objekte: 100% (789/789), 3.72 MiB | 669.00 KiB/s, done.
Löse Unterschiede auf: 100% (89/89), done.
Prüfe Konnektivität... Fertig.

[alexander@tvpi ~]$ sudo nano quake3/build.sh 

[alexander@tvpi ~]$ sudo ln -s /opt/vc/include/interface/vcos/pthreads/vcos_futex_mutex.h /opt/vc/include/interface/vcos/
[alexander@tvpi ~]$ sudo ln -s /opt/vc/include/interface/vcos/pthreads/vcos_platform.h /opt/vc/include/interface/vcos/
[alexander@tvpi ~]$ sudo ln -s /opt/vc/include/interface/vcos/pthreads/vcos_platform_types.h /opt/vc/include/interface/vcos/

[alexander@tvpi ~]$ cd quake3/
[alexander@tvpi quake3]$ chmod +x ./build.sh 
[alexander@tvpi quake3]$ ./build.sh 
make[1]: Entering directory '/home/alexander/quake3'

Building ioquake3 in build/release-linux-arm:
  PLATFORM: linux
  ARCH: arm
  VERSION: 1.35
  COMPILE_PLATFORM: linux
  COMPILE_ARCH: armv6l
  CC: gcc

  CFLAGS:
    -DVCMODS_MISC
    -DVCMODS_OPENGLES
    -DVCMODS_DEPTH
    -DVCMODS_REPLACETRIG
    -I/opt/vc/include
    -MMD
    -Wall
    -fno-strict-aliasing
    -Wimplicit
    -Wstrict-prototypes
    -pipe
    -DUSE_ICON
    -I/usr/include/SDL
    -D_GNU_SOURCE=1
    -D_REENTRANT
    -DNO_VM_COMPILED
    -Icode/SDL12/include
    -DUSE_MUMBLE
    -DUSE_VOIP
    -DFLOATING_POINT
    -DUSE_ALLOCA
    -Icode/libspeex/include
    -DUSE_LOCAL_HEADERS
    -DPRODUCT_VERSION="1.35"
    -DNDEBUG
    -O3
    -ffast-math
    -funroll-loops
    -fomit-frame-pointer

  LDFLAGS:
    -L/opt/vc/lib
    -Llib
    -lSDL
    -lvchostif
    -lvmcs_rpc_client
    -lvcfiled_check
    -lpthread
    -lbcm_host
    -lkhrn_static
    -lvchiq_arm
    -lopenmaxil
    -lEGL
    -lGLESv2
    -lvcos
    -lrt

  LIBS:
    -ldl
    -lm

  Output:
    build/release-linux-arm/ioq3ded.arm
    build/release-linux-arm/ioquake3.arm
    build/release-linux-arm/baseq3/cgamearm.so
    build/release-linux-arm/baseq3/qagamearm.so
    build/release-linux-arm/baseq3/uiarm.so
    build/release-linux-arm/missionpack/cgamearm.so
    build/release-linux-arm/missionpack/qagamearm.so
    build/release-linux-arm/missionpack/uiarm.so

make[2]: Entering directory '/home/alexander/quake3'
DED_CC code/server/sv_bot.c
DED_CC code/server/sv_client.c
DED_CC code/server/sv_ccmds.c
DED_CC code/server/sv_game.c
code/server/sv_client.c: In Funktion »SV_IsBanned«:
code/server/sv_client.c:237:13: Warnung: Variable »addrlen« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int index, addrlen, curbyte, netmask, cmpmask;
             ^
code/server/sv_game.c: In Funktion »SV_inPVSIgnorePortals«:
code/server/sv_game.c:188:14: Warnung: Variable »area2« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int  area1, area2;
              ^
code/server/sv_game.c:188:7: Warnung: Variable »area1« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int  area1, area2;
       ^
DED_CC code/server/sv_init.c
code/server/sv_init.c: In Funktion »SV_SetConfigstring«:
code/server/sv_init.c:107:7: Warnung: Variable »len« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int  len, i;
       ^
DED_CC code/server/sv_main.c
DED_CC code/server/sv_net_chan.c
code/server/sv_net_chan.c: In Funktion »SV_Netchan_Encode«:
code/server/sv_net_chan.c:37:7: Warnung: Variable »reliableAcknowledge« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  long reliableAcknowledge, i, index;
       ^
DED_CC code/server/sv_snapshot.c
DED_CC code/server/sv_world.c
code/server/sv_snapshot.c: In Funktion »SV_AddEntitiesVisibleFromPoint«:
code/server/sv_snapshot.c:301:7: Warnung: Variable »c_fullsend« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int  c_fullsend;
       ^
code/server/sv_world.c: In Funktion »SV_AreaEntities_r«:
code/server/sv_world.c:385:8: Warnung: Variable »count« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int   count;
        ^
code/server/sv_world.c: In Funktion »SV_PointContents«:
code/server/sv_world.c:663:10: Warnung: Variable »angles« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  float  *angles;
          ^
DED_CC code/qcommon/cm_load.c
DED_CC code/qcommon/cm_patch.c
DED_CC code/qcommon/cm_polylib.c
DED_CC code/qcommon/cm_test.c
DED_CC code/qcommon/cm_trace.c
DED_CC code/qcommon/cmd.c
code/qcommon/cm_trace.c: In Funktion »CM_TraceThroughSphere«:
code/qcommon/cm_trace.c:735:8: Warnung: Variable »a« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  float a, b, c, d, sqrtd;
        ^
code/qcommon/cm_trace.c: In Funktion »CM_TraceThroughVerticalCylinder«:
code/qcommon/cm_trace.c:823:8: Warnung: Variable »a« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  float a, b, c, d, sqrtd;
        ^
DED_CC code/qcommon/common.c
code/qcommon/cmd.c: In Funktion »Cmd_Exec_f«:
code/qcommon/cmd.c:246:7: Warnung: Variable »len« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int  len;
       ^
code/qcommon/common.c: In Funktion »Z_TagMalloc«:
code/qcommon/common.c:925:14: Warnung: Variable »allocSize« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int  extra, allocSize;
              ^
code/qcommon/common.c: In Funktion »Com_Frame«:
code/qcommon/common.c:2820:6: Warnung: Variable »key« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int key;
      ^
DED_CC code/qcommon/cvar.c
code/qcommon/cvar.c: In Funktion »Cvar_Restart_f«:
code/qcommon/cvar.c:925:30: Warnung: Argument für »sizeof« in Aufruf von »memset« ist der gleiche Ausdruck wie das Ziel; sollte es dereferenziert werden? [-Wsizeof-pointer-memaccess]
    Com_Memset( var, 0, sizeof( var ) );
                              ^
DED_CC code/qcommon/files.c
code/qcommon/files.c: In Funktion »FS_ComparePaks«:
code/qcommon/files.c:2562:20: Warnung: Variable »badchecksum« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  qboolean havepak, badchecksum;
                    ^
DED_CC code/qcommon/md4.c
DED_CC code/qcommon/msg.c
DED_CC code/qcommon/net_chan.c
DED_CC code/qcommon/net_ip.c
code/qcommon/net_chan.c: In Funktion »Netchan_Process«:
code/qcommon/net_chan.c:306:8: Warnung: Variable »qport« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int   qport;
        ^
code/qcommon/net_ip.c: In Funktion »NET_OpenSocks«:
code/qcommon/net_ip.c:1045:10: Warnung: Variable »err« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int     err;
          ^
DED_CC code/qcommon/huffman.c
DED_CC code/qcommon/q_math.c
DED_CC code/qcommon/q_shared.c
code/qcommon/q_shared.c: In Funktion »Q_isanumber«:
code/qcommon/q_shared.c:713:9: Warnung: Variable »d« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  double d;
         ^
DED_CC code/qcommon/unzip.c
code/qcommon/unzip.c: In Funktion »unzlocal_getShort«:
code/qcommon/unzip.c:1112:9: Warnung: Variable »size« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  size_t size;
         ^
code/qcommon/unzip.c: In Funktion »unzlocal_getLong«:
code/qcommon/unzip.c:1142:9: Warnung: Variable »size« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  size_t size;
         ^
code/qcommon/unzip.c: In Funktion »unzReadCurrentFile«:
code/qcommon/unzip.c:2048:16: Warnung: Variable »bufBefore« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
    const Byte *bufBefore;
                ^
DED_CC code/qcommon/vm.c
code/qcommon/vm.c: In Funktion »VM_LoadSymbols«:
code/qcommon/vm.c:221:7: Warnung: Variable »len« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int  len;
       ^
code/qcommon/vm.c: In Funktion »VM_LoadQVM«:
code/qcommon/vm.c:368:10: Warnung: Variable »length« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int     length;
          ^
DED_CC code/qcommon/vm_interpreted.c
BOT_CC code/botlib/be_aas_bspq3.c
BOT_CC code/botlib/be_aas_cluster.c
BOT_CC code/botlib/be_aas_debug.c
BOT_CC code/botlib/be_aas_entity.c
BOT_CC code/botlib/be_aas_file.c
BOT_CC code/botlib/be_aas_main.c
BOT_CC code/botlib/be_aas_move.c
BOT_CC code/botlib/be_aas_optimize.c
code/botlib/be_aas_move.c: In Funktion »AAS_AirControl«:
code/botlib/be_aas_move.c:392:9: Warnung: Variable »dir« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  vec3_t dir;
         ^
code/botlib/be_aas_move.c: In Funktion »AAS_ClientMovementPrediction«:
code/botlib/be_aas_move.c:521:35: Warnung: Variable »ax« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int n, i, j, pc, step, swimming, ax, crouch, event, jump_frame, areanum;
                                   ^
BOT_CC code/botlib/be_aas_reach.c
code/botlib/be_aas_reach.c: In Funktion »AAS_BestReachableFromJumpPadArea«:
code/botlib/be_aas_reach.c:292:6: Warnung: Variable »area2num« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int area2num, ent, bot_visualizejumppads, bestareanum;
      ^
code/botlib/be_aas_reach.c: In Funktion »AAS_Reachability_Swim«:
code/botlib/be_aas_reach.c:840:22: Warnung: Variable »areasettings« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  aas_areasettings_t *areasettings;
                      ^
code/botlib/be_aas_reach.c: In Funktion »AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge«:
code/botlib/be_aas_reach.c:1076:61: Warnung: Variable »water_bestface1« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  aas_face_t *groundface1, *groundface2, *ground_bestface1, *water_bestface1;
                                                             ^
code/botlib/be_aas_reach.c:1076:42: Warnung: Variable »ground_bestface1« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  aas_face_t *groundface1, *groundface2, *ground_bestface1, *water_bestface1;
                                          ^
code/botlib/be_aas_reach.c:1065:34: Warnung: Variable »invgravitydot« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  float dist, dist1, dist2, diff, invgravitydot, ortdot;
                                  ^
code/botlib/be_aas_reach.c: In Funktion »AAS_Reachability_JumpPad«:
code/botlib/be_aas_reach.c:3495:21: Warnung: Variable »hordist« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  float speed, zvel, hordist;
                     ^
code/botlib/be_aas_reach.c: In Funktion »AAS_Reachability_WeaponJump«:
code/botlib/be_aas_reach.c:4000:21: Warnung: Variable »hordist« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  float speed, zvel, hordist;
                     ^
BOT_CC code/botlib/be_aas_route.c
code/botlib/be_aas_route.c: In Funktion »AAS_CalculateAreaTravelTimes«:
code/botlib/be_aas_route.c:509:6: Warnung: Variable »starttime« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int starttime;
      ^
code/botlib/be_aas_route.c: In Funktion »AAS_CreateAllRoutingCache«:
code/botlib/be_aas_route.c:890:12: Warnung: Variable »t« gesetzt, aber nicht verwendet [-Wunused-but-set-variable]
  int i, j, t;
            ^
gcc: interner Compiler-Fehler: Getötet (Programm cc1)
Bitte senden Sie einen vollständigen Fehlerbericht auf Englisch ein;
bearbeiten Sie die Quellen zunächst mit einem Präprozessor, wenn es
dienlich ist.
Siehe <https://github.com/archlinuxarm/PKGBUILDs/issues> für nähere Anweisungen.
Makefile:1996: recipe for target 'build/release-linux-arm/ded/unzip.o' failed
make[2]: *** [build/release-linux-arm/ded/unzip.o] Error 4
make[2]: *** Warte auf noch nicht beendete Prozesse...
code/botlib/be_aas_route.c:1755:5: Warnung: »reachnum« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
  if (bestreachnum < 0) {
     ^
code/botlib/be_aas_route.c:1770:18: Anmerkung: »reachnum« wurde hier deklariert
  int traveltime, reachnum;
                  ^
code/botlib/be_aas_route.c: In Funktion »AAS_AreaTravelTimeToGoalArea«:
code/botlib/be_aas_route.c:1755:5: Warnung: »reachnum« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
  if (bestreachnum < 0) {
     ^
code/botlib/be_aas_route.c:1770:18: Anmerkung: »reachnum« wurde hier deklariert
  int traveltime, reachnum;
                  ^
code/botlib/be_aas_route.c: In Funktion »AAS_AreaReachabilityToGoalArea«:
code/botlib/be_aas_route.c:1755:5: Warnung: »reachnum« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
  if (bestreachnum < 0) {
     ^
code/botlib/be_aas_route.c:1786:18: Anmerkung: »reachnum« wurde hier deklariert
  int traveltime, reachnum;
                  ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/be_aas_reach.c: In Funktion »AAS_Reachability_Jump«:
code/botlib/../qcommon/q_shared.h:439:83: Warnung: »*((void *)&bestend2+8)« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorAdd(a,b,c)  ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
                                                                                   ^
code/botlib/be_aas_reach.c:2115:41: Anmerkung: »*((void *)&bestend2+8)« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2;
                                         ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:439:62: Warnung: »*((void *)&bestend2+4)« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorAdd(a,b,c)  ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
                                                              ^
code/botlib/be_aas_reach.c:2115:41: Anmerkung: »*((void *)&bestend2+4)« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2;
                                         ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:439:41: Warnung: »bestend2« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorAdd(a,b,c)  ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
                                         ^
code/botlib/be_aas_reach.c:2115:41: Anmerkung: »bestend2« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2;
                                         ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:439:83: Warnung: »*((void *)&beststart2+8)« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorAdd(a,b,c)  ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
                                                                                   ^
code/botlib/be_aas_reach.c:2115:20: Anmerkung: »*((void *)&beststart2+8)« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2;
                    ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:439:62: Warnung: »*((void *)&beststart2+4)« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorAdd(a,b,c)  ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
                                                              ^
code/botlib/be_aas_reach.c:2115:20: Anmerkung: »*((void *)&beststart2+4)« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2;
                    ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:439:41: Warnung: »beststart2« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorAdd(a,b,c)  ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
                                         ^
code/botlib/be_aas_reach.c:2115:20: Anmerkung: »beststart2« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2;
                    ^
code/botlib/be_aas_route.c: In Funktion »AAS_RandomGoalArea«:
code/botlib/be_aas_route.c:1755:5: Warnung: »reachnum« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
  if (bestreachnum < 0) {
     ^
code/botlib/be_aas_route.c:1770:18: Anmerkung: »reachnum« wurde hier deklariert
  int traveltime, reachnum;
                  ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/be_aas_reach.c: In Funktion »AAS_FindFaceReachabilities«:
code/botlib/../qcommon/q_shared.h:438:87: Warnung: »*((void *)&bestend2+8)« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorSubtract(a,b,c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
                                                                                       ^
code/botlib/be_aas_reach.c:3159:41: Anmerkung: »*((void *)&bestend2+8)« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2, tmp, hordir, testpoint;
                                         ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:438:66: Warnung: »*((void *)&bestend2+4)« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorSubtract(a,b,c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
                                                                  ^
code/botlib/be_aas_reach.c:3159:41: Anmerkung: »*((void *)&bestend2+4)« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2, tmp, hordir, testpoint;
                                         ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:438:45: Warnung: »bestend2« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorSubtract(a,b,c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
                                             ^
code/botlib/be_aas_reach.c:3159:41: Anmerkung: »bestend2« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2, tmp, hordir, testpoint;
                                         ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:438:87: Warnung: »*((void *)&beststart2+8)« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorSubtract(a,b,c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
                                                                                       ^
code/botlib/be_aas_reach.c:3159:20: Anmerkung: »*((void *)&beststart2+8)« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2, tmp, hordir, testpoint;
                    ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:438:66: Warnung: »*((void *)&beststart2+4)« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorSubtract(a,b,c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
                                                                  ^
code/botlib/be_aas_reach.c:3159:20: Anmerkung: »*((void *)&beststart2+4)« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2, tmp, hordir, testpoint;
                    ^
In file included from code/botlib/be_aas_reach.c:32:0:
code/botlib/../qcommon/q_shared.h:438:45: Warnung: »beststart2« könnte in dieser Funktion uninitialisiert verwendet werden [-Wmaybe-uninitialized]
 #define VectorSubtract(a,b,c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
                                             ^
code/botlib/be_aas_reach.c:3159:20: Anmerkung: »beststart2« wurde hier deklariert
  vec3_t beststart, beststart2, bestend, bestend2, tmp, hordir, testpoint;
                    ^
make[2]: Leaving directory '/home/alexander/quake3'
Makefile:981: recipe for target 'targets' failed
make[1]: *** [targets] Error 2
make[1]: Leaving directory '/home/alexander/quake3'
Makefile:975: recipe for target 'release' failed
make: *** [release] Error 2
[alexander@tvpi quake3]$

**Comment by Ruffio** [comment]
@Klex167 is this still an issue?

**Comment by Klex167** [comment]
No, i compiled it with Raspian and run the game with arch linux.

**Comment by kriekprinsloo** [comment]
Is it possible to compile and run this on a computer that is not a Raspberry Pi, but still a Linux based operating system(e.g Ubuntu)?
