### ISSUE TITLE
Spammer in your README

### ISSUE THREAD

**Issue by Sonophoto** [raspberrypi/quake3#7]
In the main readme users are referrered to: 

http://www.qeradiant.com/ 

it is some sort of Advertising carousel not a quake site.

**Comment by popcornmix** [comment]
The link was valid, but it seems the address has changed and the old address is a placeholder with adverts.
Looks like http://icculus.org/gtkradiant/ is the updated url.
See: https://github.com/ioquake/ioq3

The README wasn't written by us. Perhaps updating repo to latest ioq3 code would be the best solution.

**Comment by Sonophoto** [comment]
Are you serious??? I think YOU need to update YOUR repo :-)

Reported to github security.

**Comment by popcornmix** [comment]
URL has been updated.
